version: "2"

services:
  local-pull-executor:
    image: ghcr.io/aida-monitor/local-pull-executor:latest
    restart: always
    container_name: local-pull-executor
    network_mode: bridge
    environment:
      ORGANIZATION_NAME: ${ORGANIZATION_NAME}
      CORE_URL: ${CORE_URL}
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}

  local-push-receiver:
    image: ghcr.io/aida-monitor/local-push-receiver:latest
    restart: always
    container_name: local-push-receiver
    network_mode: bridge
    ports:
      - "6000:3000"
    environment:
      CORE_URL: ${CORE_URL}
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
