version: "2"

services:
    influxdb:
        image: influxdb:2.1
        container_name: influxdb
        restart: always
        networks:
            - aida-monit-net
        ports:
            - 8087:8086
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
            DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
        volumes:
            - influxdb-data:/var/lib/influxdb2
            - influxdb-config:/etc/influxdb2
    
    mongodb:
        image: mongo:latest
        container_name: mongodb
        networks:
            - aida-monit-net
        restart: always
        ports:
            - 27018:27017
        volumes:
            - mongodb-data:/data/db

    core:
        image: ghcr.io/aida-monitor/core:latest
        restart: always
        container_name: core
        networks:
            - aida-monit-net
        ports:
            - 3000:3000
        environment:
            MONGODB_URL: ${MONGODB_URL}
            INFLUXDB_URL: ${INFLUXDB_URL}
            INFLUXDB_ORG: ${INFLUXDB_ORG}
            INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
            INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
            JWT_SECRET: ${JWT_SECRET}
            NODE_ENV: ${NODE_ENV:-production}
        depends_on:
            - influxdb
            - mongodb

    alert-manager:
        image: ghcr.io/aida-monitor/alert-manager:latest
        restart: always
        container_name: alert-manager
        ports:
            - 3001:3000
        environment:
            MONGODB_URL: ${MONGODB_URL}
            INFLUXDB_URL: ${INFLUXDB_URL}
            INFLUXDB_ORG: ${INFLUXDB_ORG}
            INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
            INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
            JWT_SECRET: ${JWT_SECRET}
            NODE_ENV: ${NODE_ENV:-development}
        depends_on:
            - influxdb
            - mongodb
    
    auth:
        image:  ghcr.io/aida-monitor/auth-mock:latest
        container_name: auth
        networks:
            - aida-monit-net
        restart: always
        ports:
            - 3002:3000
        environment:
            JWT_SECRET: ${JWT_SECRET}
            NODE_ENV: ${NODE_ENV:-production}


volumes:
    influxdb-data:
    influxdb-config:
    mongodb-data:


networks:
    aida-monit-net:
        driver: bridge
