version: "3.8"

services:
  local-pull-executor:
    build: ../local-pull-executor
    restart: always
    container_name: local-local-pull-executor
    environment:
      ORGANIZATION_NAME: ${ORGANIZATION_NAME}
      CORE_URL: ${CORE_URL}
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV:-production}

  local-push-receiver:
    build: ../local-push-receiver
    restart: always
    container_name: local-push-receiver
    ports:
      - "6000:3000"
    environment:
      ORGANIZATION_NAME: ${ORGANIZATION_NAME}
      CORE_URL: ${CORE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV:-production}