version: "3.8"

services:
  kong:
    build: ../kong
    restart: always
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yml"
      KONG_PLUGINS: "bundled,custom-auth,path-prefix"
    ports:
      - "8000:8000"

  auth-mock:
    build: ../auth-mock
    restart: always
    container_name: auth-mock
    ports:
      - "4500:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}

  influxdb:
    image: influxdb:2.1
    restart: always
    container_name: influxdb
    ports:
      - "8087:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

  mongodb:
    image: mongo:5.0
    restart: always
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_APP_DATABASE}
      MONGODB_APP_USERNAME: ${MONGODB_APP_USERNAME}
      MONGODB_APP_PASSWORD: ${MONGODB_APP_PASSWORD}
    volumes:
      - mongodb-data:/data/db
      - ./mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  core:
    build: ../core
    restart: always
    container_name: core
    ports:
      - "3001:3000"
    environment:
      ALERTS_MANAGER_URL: http://alert-manager:3000
      MONGODB_URL: mongodb://${MONGODB_APP_USERNAME}:${MONGODB_APP_PASSWORD}@mongodb:27017/${MONGODB_APP_DATABASE}?readPreference=primary&ssl=false
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV:-production}
    depends_on:
      - influxdb
      - mongodb
      - alert-manager

  alert-manager:
    build: ../alert-manager
    restart: always
    container_name: alert-manager
    ports:
      - "3002:3000"
    environment:
      MONGODB_URL: mongodb://${MONGODB_APP_USERNAME}:${MONGODB_APP_PASSWORD}@mongodb:27017/${MONGODB_APP_DATABASE}?readPreference=primary&ssl=false
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV:-production}
    depends_on:
      - influxdb
      - mongodb

  data-exporter:
    build: ../data-exporter
    restart: always
    container_name: data-exporter
    ports:
      - "3003:3000"
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV:-production}
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  influxdb-config:
  mongodb-data:
